table 'Sales by Store'
	lineageTag: 26f12790-5340-4c97-a4ac-dec619a2f964

	column transaction_id
		dataType: int64
		formatString: 0
		lineageTag: 8a82451c-cc61-49ae-93c0-67fd7e844ccd
		summarizeBy: sum
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column transaction_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7888930b-dd13-4bac-b8eb-8eaff4cae190
		summarizeBy: none
		sourceColumn: transaction_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column transaction_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 3478587b-26f9-4670-9c18-41e5a4f92910
		summarizeBy: none
		sourceColumn: transaction_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: 5c300920-9335-49a2-9e8a-6f58aa6970e0
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column staff_id
		dataType: int64
		formatString: 0
		lineageTag: 33fc237a-9997-42d9-a647-4f69f8c01db3
		summarizeBy: none
		sourceColumn: staff_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: a0cfc165-cee3-4a8c-aaa7-95b29248157b
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column instore_yn
		dataType: string
		lineageTag: 79e182c6-ebb1-4ce2-8bd7-231ac285ae1d
		summarizeBy: none
		sourceColumn: instore_yn

		annotation SummarizationSetBy = Automatic

	column order
		dataType: int64
		formatString: 0
		lineageTag: 6b9ff96d-76e1-43b5-83c0-4507a63ef722
		summarizeBy: sum
		sourceColumn: order

		annotation SummarizationSetBy = Automatic

	column line_item_id
		dataType: int64
		formatString: 0
		lineageTag: 58ceb364-627f-4d31-9a43-b90a392bc853
		summarizeBy: sum
		sourceColumn: line_item_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: cb6cacbd-e87c-4a95-a3f0-81c733c1e17e
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column quantity_sold
		dataType: int64
		formatString: 0
		lineageTag: 7f1275df-69d6-4d29-b35f-beef4615a9fe
		summarizeBy: sum
		sourceColumn: quantity_sold

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		lineageTag: 95c44615-3661-4616-828c-37598dda86f2
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column promo_item_yn
		dataType: string
		lineageTag: ef064968-abbb-4ad1-a7e2-cbd1c00701da
		summarizeBy: none
		sourceColumn: promo_item_yn

		annotation SummarizationSetBy = Automatic

	column 'Time Group' =
			
			FLOOR(
			    'Sales by Store'[transaction_time],
			    "1:00"
			)
		dataType: dateTime
		formatString: Long Time
		lineageTag: 0e62e1c0-1a87-4fc8-a0c9-783390666321
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Total Revenue' =
			
			CURRENCY(
			    'Sales by Store'[quantity_sold]* 'Sales by Store'[unit_price]
			)
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 0ee16b88-01a3-49f6-8d80-b4e83d1ba63a
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition 'Sales by Store' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NdivhudzannyiT\OneDrive - Northern Data (Pty) Ltd\Documents\Udemy Course\Microsoft Power BI\Advanced DAX for Data Analysis\Advanced+DAX+Data+Files\Advanced DAX Data Files\Sales by Store.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"transaction_id", Int64.Type}, {"transaction_date", type date}, {"transaction_time", type time}, {"store_id", Int64.Type}, {"staff_id", Int64.Type}, {"customer_id", Int64.Type}, {"instore_yn", type text}, {"order", Int64.Type}, {"line_item_id", Int64.Type}, {"product_id", Int64.Type}, {"quantity_sold", Int64.Type}, {"unit_price", type number}, {"promo_item_yn", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

