table 'ActiveCustomer Lookup'
	lineageTag: 46c4488a-959d-41aa-86fd-042b97590d8d

	column ActiveID
		dataType: int64
		formatString: 0
		lineageTag: 499db0c1-58b0-4ca7-8756-a129c140b8b2
		summarizeBy: none
		sourceColumn: ActiveID

		annotation SummarizationSetBy = Automatic

	column ActiveCategory
		dataType: string
		lineageTag: 8c1737f7-db2b-43f0-a268-93f4598fe2fc
		summarizeBy: none
		sourceColumn: ActiveCategory

		annotation SummarizationSetBy = Automatic

	partition 'ActiveCustomer Lookup' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\NdivhudzannyiT\Documents\Ndivhu_Tshikho\Data\YouTube Project Datasets\Data Sets for end to end Powerbi Project\ActiveCustomer.xlsx"), null, true),
				    ActiveCustomer_Sheet = Source{[Item="ActiveCustomer",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(ActiveCustomer_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ActiveID", Int64.Type}, {"ActiveCategory", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

