DEFINE
	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL('Calendar'[Transaction_Date], "IsGrandTotalRowTotal"),
			"Customer_Sales__Last_Year_", 'Measure Table'[Customer Sales (Last Year)]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(502, __DS0Core, [IsGrandTotalRowTotal], 0, 'Calendar'[Transaction_Date], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[IsGrandTotalRowTotal] DESC, 'Calendar'[Transaction_Date]