table Sales
	lineageTag: 1a1011df-df53-4630-8026-6f2a4b145487

	column fSalesPrimaryKey
		dataType: int64
		formatString: 0
		lineageTag: eebb0452-8824-4d24-a4ca-730d97a3e372
		summarizeBy: count
		sourceColumn: fSalesPrimaryKey

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 6ae95136-b605-4613-8314-04b8928afa92
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: 35090bd4-f178-452a-a535-f8927d09f6a6
		summarizeBy: none
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5514f74a-2675-4dc4-a06b-a735d9952e11
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Units
		dataType: int64
		formatString: 0
		lineageTag: 4e089f94-c34f-4175-a829-be6b38d529b8
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	column PercentOfStandardCost
		dataType: double
		lineageTag: d93f770a-bb45-46fe-bcbb-e4f73a45b760
		summarizeBy: sum
		sourceColumn: PercentOfStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RevenueDiscount
		dataType: double
		lineageTag: dd96ba1f-de86-48d6-a797-6524089d1424
		summarizeBy: sum
		sourceColumn: RevenueDiscount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GeoKey
		dataType: int64
		formatString: 0
		lineageTag: 40a80203-ee78-41cc-bab6-330a394b946e
		summarizeBy: none
		sourceColumn: GeoKey

		annotation SummarizationSetBy = Automatic

	column 'Total Reveue' = Sales[Units]* RELATED('Profile Lookup'[RetailPrice])
		dataType: double
		formatString: 0.00
		lineageTag: 6f453653-b757-492a-a028-0b3033ed24f9
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Total Cost' = Sales[Units] * RELATED('Profile Lookup'[StandardCost])
		dataType: double
		formatString: 0.00
		lineageTag: 6bbf083f-cf26-4697-9b63-552ed9082179
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Gross Profit' = Sales[Total Reveue] - Sales[Total Cost]
		dataType: double
		lineageTag: 4514a6c7-2480-45d0-a952-1558b84a5e95
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\NdivhudzannyiT\Documents\Ndivhu_Tshikho\Data\YouTube Project Datasets\Sales"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"fSalesPrimaryKey", Int64.Type}, {"ProductID", Int64.Type}, {"SalesRepID", Int64.Type}, {"Location", type text}, {"Date", type date}, {"Units", Int64.Type}, {"PercentOfStandardCost", type number}, {"RevenueDiscount", type number}}),
				    #"Removed Source Details" = Table.RemoveColumns(#"Changed Type",{"Source.Name"}),
				    #"Split location" = Table.SplitColumn(#"Removed Source Details", "Location", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"Location.1", "Location.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split location",{{"Location.1", type text}, {"Location.2", type text}}),
				    #"Renamed Columns to location 1 to Country and Location 2 to town" = Table.RenameColumns(#"Changed Type1",{{"Location.1", "Country"}, {"Location.2", "Town"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns to location 1 to Country and Location 2 to town", {"Town"}, #"Geography Lookup", {"Town"}, "Geography Lookup", JoinKind.LeftOuter),
				    #"Expanded Geography Lookup" = Table.ExpandTableColumn(#"Merged Queries", "Geography Lookup", {"GeoKey"}, {"Geography Lookup.GeoKey"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded Geography Lookup",{"fSalesPrimaryKey", "ProductID", "SalesRepID", "Geography Lookup.GeoKey", "Country", "Town", "Date", "Units", "PercentOfStandardCost", "RevenueDiscount"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Geography Lookup.GeoKey", "GeoKey"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"Country", "Town"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

