# Use the official Nginx image as the base image
FROM nginx:latest

# Copy your custom Nginx config file into the container
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose port 80 for web traffic
EXPOSE 80

