table 'Calendar Lookup'

	measure Measure

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Adjusted Price' = [Average Retail Price] * (1+'Price Adjustment '[Price Adjustment  Value])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Day Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Start of Week'
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: Start of Week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Month'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Start of Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Quarter'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Start of Quarter

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Start of Year'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: Start of Year

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Number (DAX)' =
			
			SWITCH(
			    'Calendar Lookup'[Month Name],
			    "January", "1",
			    "February", "2",
			    "March", "3",
			    "April", "4",
			    "May", "5",
			    "June", "6",
			    "July", "7",
			    "August", "8",
			    "September", "9",
			    "October", "10",
			    "November", "11",
			    "December", "12",
			    "Other"
			)
		dataType: string
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Month Short' =
			
			UPPER(
			    LEFT(
			        'Calendar Lookup'[Month Name],3
			    )
			)
		dataType: string
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Day of Week' =
			
			
			WEEKDAY(
			    'Calendar Lookup'[Date],2
			    )
		dataType: int64
		formatString: 0
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column Weekend =
			
			if(
			    'Calendar Lookup'[Day of Week] IN {6, 7},
			    "Weekend",
			    "Weekday"
			)
		dataType: string
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	hierarchy Hierarchy
		isHidden

		level 'Start of Year'
			column: 'Start of Year'

		level 'Start of Quarter'
			column: 'Start of Quarter'

		level 'Start of Week'
			column: 'Start of Week'

		level 'Start of Month'
			column: 'Start of Month'

		changedProperty = IsHidden

	hierarchy 'Date Hierarchy'

		level 'Start of Year'
			column: 'Start of Year'

		level 'Start of Month'
			column: 'Start of Month'

		level 'Start of Week'
			column: 'Start of Week'

	partition 'Calendar Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NdivhudzannyiT\OneDrive - Northern Data (Pty) Ltd\Documents\Udemy Course\Microsoft Power BI\AdventureWorks+Raw+Data\AdventureWorks Raw Data\AdventureWorks Calendar Lookup.csv"),[Delimiter=",", Columns=1, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}}),
				    #"Inserted Day Name" = Table.AddColumn(#"Changed Type", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Day Name", "Start of Week", each Date.StartOfWeek([Date],Day.Monday)),
				    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Start of Week", "Start of Month", each Date.StartOfMonth([Date]), type date),
				    #"Inserted Start of Quarter" = Table.AddColumn(#"Inserted Start of Month", "Start of Quarter", each Date.StartOfQuarter([Date]), type date),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted Start of Quarter", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Month Name", "Month", each Date.Month([Date]), Int64.Type),
				    #"Inserted Start of Year" = Table.AddColumn(#"Inserted Month", "Start of Year", each Date.StartOfYear([Date]), type date),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Start of Year", "Year", each Date.Year([Date]), Int64.Type),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Year",{{"Start of Week", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

