table 'Price Adjustment '

	measure 'Price Adjustment  Value' = SELECTEDVALUE('Price Adjustment '[Price Adjustment ], 0)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Price Adjustment '
		dataType: double
		summarizeBy: none
		isDataTypeInferred
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Price Adjustment ' = calculated
		mode: import
		source = GENERATESERIES(-1, 1, 0.1)

	annotation PBI_Id = a0df86925a1a4a5d979c23138791e3c0

