
services:
  frontend-service:
    build:
      context: ./frontend-service  # Path to the frontend service directory
    ports:
      - "8000:8000"                 # Expose port 8000 for the frontend service
    volumes:
      - ./frontend-service/app:/app  # Bind mount the app directory for live updates

  user-service:
    build:
      context: ./user-service  # Path to the user service directory
    ports:
      - "8001:8000"            # Expose port 8000 for the user service

  product-service:
    build:
      context: ./product-service  # Path to the product service directory
    ports:
      - "8002:8000"               # Expose port 8000 for the product service

  nginx:
    build:
      context: ./nginx  # Path to the Nginx directory
    ports:
      - "8080:80"       # Expose port 8080 for Nginx
    depends_on:
      - frontend-service
      - user-service
      - product-service
    volumes:
      - ./frontend-service/app/static:/usr/share/nginx/html/static  # Serve static files
      - ./frontend-service/app/templates:/usr/share/nginx/html       # Serve HTML templates
