services:
  product-service:
    build: ./product-service
    ports:
      - "8001:8000"
    networks:
      - ecommerce-network
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    ports:
      - "8002:8000"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
