version: '3.8'

services:
  product-service:
    build: ./product-service
    ports:
      - "8001:8001"
    networks:
      - ecommerce-network
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    ports:
      - "8002:8002"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
