services:
  user_service:
    build:
      context: ./user-service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:///./user.db
    volumes:
      - ./user-service/app:/app

  product_service:
    build:
      context: ./product-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=sqlite:///./product.db
    volumes:
      - ./product-service/app:/app

  frontend_service:
    build:
      context: ./frontend-service
    ports:
      - "5000:5000"
    volumes:
      - ./frontend-service/app:/app
    depends_on:
      - user_service
      - product_service
