table Sales
	lineageTag: 88b6ee38-8270-437e-b394-77125613d2d5

	column fSalesPrimaryKey
		dataType: int64
		formatString: 0
		lineageTag: 0ecf8a0c-a15d-407f-a7d8-3f5182ca9247
		summarizeBy: count
		sourceColumn: fSalesPrimaryKey

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: e22768e6-0d07-4f81-a89d-0c7df77a2b7f
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: 9ea0650a-7635-41c0-b443-1632791e8113
		summarizeBy: none
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column 'Geo.Key'
		dataType: int64
		formatString: 0
		lineageTag: af79fa57-f842-4e2f-9966-b142cfd1dcc3
		summarizeBy: none
		sourceColumn: Geo.Key

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: int64
		formatString: 0
		lineageTag: ed5f1c9c-d158-4ba4-a8da-aa69f3491e48
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	column PercentOfStandardCost
		dataType: double
		lineageTag: ceea7ee6-23ce-404f-8d6b-c858c7f010b6
		summarizeBy: sum
		sourceColumn: PercentOfStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RevenueDiscount
		dataType: double
		lineageTag: e1de526f-2d29-430a-b96b-009c96cb839a
		summarizeBy: sum
		sourceColumn: RevenueDiscount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a57e331e-8353-46e1-aa46-79961a45a1d8
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Total Revenue' = Sales[Units]*RELATED('Product Lookup'[RetailPrice])
		dataType: double
		formatString: #,0.00
		lineageTag: b09b1172-32b5-4262-9459-60f883aa053f
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Total Cost' = Sales[Units]*RELATED('Product Lookup'[StandardCost])
		dataType: double
		formatString: #,0.00
		lineageTag: 7921f9e8-aad5-4925-91a4-8143f878c4de
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column 'Gross Profit' = Sales[Total Revenue] - Sales[Total Cost]
		dataType: double
		formatString: #,0.00
		lineageTag: 7592dfe7-756e-4f94-95ef-7b25fa0fa666
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\NdivhudzannyiT\Documents\Ndivhu_Tshikho\Data\YouTube Project Datasets\Sales"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"fSalesPrimaryKey", Int64.Type}, {"ProductID", Int64.Type}, {"SalesRepID", Int64.Type}, {"Location", type text}, {"Date", type date}, {"Units", Int64.Type}, {"PercentOfStandardCost", type number}, {"RevenueDiscount", type number}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Location", Splitter.SplitTextByDelimiter(";", QuoteStyle.Csv), {"Location.1", "Location.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Location.1", type text}, {"Location.2", type text}}),
				    #"Renamed Columns split location into country and Town" = Table.RenameColumns(#"Changed Type1",{{"Location.1", "Country"}, {"Location.2", "Town"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns split location into country and Town",{"Source.Name"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"Country", "Town"}, #"Geography Lookup", {"Country", "Town"}, "Geography Lookup", JoinKind.LeftOuter),
				    #"Expanded Geography Lookup" = Table.ExpandTableColumn(#"Merged Queries", "Geography Lookup", {"Geo.Key"}, {"Geography Lookup.Geo.Key"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Geography Lookup",{{"Geography Lookup.Geo.Key", "Geo.Key"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"fSalesPrimaryKey", "ProductID", "SalesRepID", "Geo.Key", "Country","Town", "Date", "Units", "PercentOfStandardCost", "RevenueDiscount"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns",{"Country", "Town"}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Columns1", {"Date"})
				in
				    #"Removed Errors"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

