name: Deploy SSIS Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: Install SQL Server module
        run: |
          Install-Module -Name SqlServer -Force -AllowClobber
          Import-Module SqlServer

      - name: Run PowerShell script
        shell: pwsh
        run: |
          $packageFilePath = "DatabaseAdministration/SSIS/SSISWorking/Aggregate.dtsx"

          try {
              # Load the SSIS assembly
              Add-Type -AssemblyName "Microsoft.SqlServer.Management.IntegrationServices" -ErrorAction Stop

              $SSISNamespace = "Microsoft.SqlServer.Management.IntegrationServices"
              $TargetServerName = "DESKTOP-PL72RR2"
              $CatalogName = "SSISDB"
              $FolderName = "SSISWorking"
              $ProjectName = "SSISWorking"
              $PackageFilePath = $Env:GITHUB_WORKSPACE + "/" + $packageFilePath

              # Create a connection to the server
              $sqlConnectionString = "Data Source=$TargetServerName;Integrated Security=True;MultipleActiveResultSets=false"
              $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString

              # Create the Integration Services object
              $integrationServices = New-Object $SSISNamespace".IntegrationServices" $sqlConnection

              # Get the folder instance
              $folder = $integrationServices.Catalogs[$CatalogName].Folders[$FolderName]

              # Read the package data from the file
              $packageData = Get-Content -Path $PackageFilePath -Raw

              # Deploy the package to the destination project
              $folder.DeployPackages($ProjectName, @{"Package" = $packageData})

              Write-Host "Package deployed successfully."
          } catch {
              Write-Error "Failed to deploy package: $_"
              exit 1
          }
