name: Deploy SSIS Package
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Install SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          sudo apt-get install -y --no-install-recommends msodbcsql17
 
      - name: Deploy SSIS package
        run: |
          # Execute SQL command to deploy the SSIS package
          sqlcmd -S "7.tcp.eu.ngrok.io,18547" -U "User" -P "Issa100@" -d SSISDB -Q "DECLARE @ProjectBinary AS varbinary(max); DECLARE @operation_id AS bigint; SET @ProjectBinary = (SELECT * FROM OPENROWSET(BULK '${{ github.workspace }}/DatabaseAdministration/SSIS/Practice Activity 2/bin/Development/Practice Activity 2.ispac', SINGLE_BLOB) AS BinaryData); EXEC catalog.deploy_project @folder_name = 'CustomerTest', @project_name = 'Practice Activity 2', @Project_Stream = @ProjectBinary, @operation_id = @operation_id out"
      - name: Debug workspace contents
        run: ls -R ${{ github.workspace }}
