name: MSSQL CI

on:
  push:
    branches:
      - main

jobs:
  run_sql_scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove conflicting package
      run: sudo apt-get remove containerd.io -y

    - name: Update package lists
      run: sudo apt-get update

    - name: Install FreeTDS and SQLCMD
      run: sudo apt-get install freetds-dev freetds-bin -y

    - name: Run SQL script
      run: |
        cat DatabaseAdministration/SQLStatement/script.sql |
        tsql -S 0.tcp.in.ngrok.io,18551 -U sa -P C8xYp!Z3#sDq
