name: MSSQL CI

on:
  push:
    branches:
      - main
    paths:
      - 'DatabaseAdministration/SQLStatement/script.sql'

jobs:
  run_sql_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove conflicting package and update package lists
        run: |
          sudo apt-get remove containerd.io -y
          sudo apt-get update

      - name: Install Docker
        run: sudo apt-get install docker.io -y

      - name: Run MSSQL Server
        run: |
          sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD= ${{secrets.DK_PASSWORD}}' -p ${{secrets.DK_PORT}} --name sql1 -d mcr.microsoft.com/mssql/server:2019-latest

      - name: Wait for MSSQL to start
        run: sleep 30

      - name: Start Docker container if not running
        run: sudo docker ps -a | grep -q 'sql1' && sudo docker start sql1 || true

      - name: Copy SQL script into a container and Run SQL script Copied in the Local Server
        run: |
          sudo docker cp DatabaseAdministration/SQLStatement/script.sql sql1:/tmp/script.sql
          sudo docker exec -i sql1 /opt/mssql-tools/bin/sqlcmd -S ${{secrets.NEW_LOCAL_SERVER_NAME}} -U ${{secrets.LOCALLOGIN}} -P ${{secrets.LOCALSERVERPASSWORD}} -i /tmp/script.sql

      - name: Check container changes and Run SQL scripts
        run: |
          sudo docker exec -i sql1 /opt/mssql-tools/bin/sqlcmd -S ${{secrets.NEW_LOCAL_SERVER_NAME}} -U ${{secrets.LOCALLOGIN}} -P ${{secrets.LOCALSERVERPASSWORD}} -Q 'SELECT name FROM sys.databases;'
