- name: Download and run MSSQL Docker container
      run: |
        sudo docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=YourStrongPassword" -p 1433:1433 --name sql_server -v $(pwd):/scripts mcr.microsoft.com/mssql/server:2019-latest

    - name: Wait for MSSQL to start
      run: |
        sleep 60 # Adjust this based on your system's startup time
        docker ps -a

    - name: Run SQL script
      run: |
        # Assuming your SQL script file is named 'script.sql' and located in the root directory of your repository
        sudo docker exec -it sql_server /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrongPassword -d master -i /scripts/script.sql
