name: MSSQL Server Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update and upgrade packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Remove conflicting package
        run: |
          sudo apt-get remove -y containerd

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Check if MSSQL container is running
        run: |
          docker ps -a | grep sql_server || true

      - name: View container logs
        run: |
          docker logs sql_server || true

      - name: Manually start MSSQL container
        run: |
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=YourStrongPassword" -p 1433:1433 --name sql_server -d mcr.microsoft.com/mssql/server:latest || true

      - name: Check if MSSQL container is running after manual start
        run: |
          docker ps -a | grep sql_server || true

      - name: Run SQL script
        if: ${{ success() }}
        run: |
          docker exec sql_server /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrongPassword -d master -i path/to/your/script.sql
