name: MSSQL CI

on:
  push:
    branches:
      - main

jobs:
  run_sql_scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker.io -y

    - name: Run MSSQL Server
      run: |
        sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrongPassword' -p 1433:1433 --name sql1 -d mcr.microsoft.com/mssql/server:2019-latest

    - name: Wait for MSSQL to start
      run: sleep 30

    - name: Run SQL scripts
      run: |
        sudo docker exec -i sql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrongPassword -d master -i script.sql

