name: Deploy Power BI Report

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Install Power BI Tools
        run: dotnet tool install --global PbiTools

      - name: Deploy Power BI Report
        run: |
          pbi-tools deploy PowerBIReports --label deploy --environment PROD --base-path PowerBIReports
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
