name: Deployment

# Controls when the workflow will run
on: 
  push:
    branches:
      - main
    paths:
      - 'PowerBIReports/Territory Lookup.pbix'
  workflow_dispatch:

jobs: 
  Deployment:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/pbi-tools-core:latest

    steps:
      # Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Authenticate with Power BI
        id: auth
        run: |
          response=$(curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=client_credentials&client_id=${{ secrets.PBI_CLIENT_ID }}&client_secret=${{ secrets.PBI_CLIENT_SECRET }}&resource=https://analysis.windows.net/powerbi/api&scope=openid" https://login.microsoftonline.com/${{ secrets.PBI_TENANT_ID }}/oauth2/token)
          echo "##vso[task.setvariable variable=PBI_ACCESS_TOKEN;issecret=true]$(echo $response | jq -r '.access_token')"

      - name: Deploy Power BI Report
        run: |
          pbi-tools publish \
            --workspace "Report DevOps Tutorial" \
            --accessToken ${{ secrets.PBI_ACCESS_TOKEN }} \
            --inputFilePath "PowerBIReports/Territory Lookup.pbix" \
            --overwrite
        env:
          PBI_ACCESS_TOKEN: ${{ secrets.PBI_ACCESS_TOKEN }}
