name: Deployment

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: PROD
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      # Deploy using pbi-tools
      - name: pbi-tools deploy
        run: |
          /app/pbi-tools/pbi-tools.core deploy . "Files" "PROD"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
          PBI_CLIENT_ID: ${{ secrets.PBI_CLIENT_ID }}
          PBI_TENANT_ID: ${{ secrets.PBI_TENANT_ID }}
