name: DeployReport

on:
  push:
    branches:
      - main

jobs:
  deploy_report:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Publish Report to Web Report Server
        run: |
          # PowerShell script to publish report to Web Report Server
          $reportPath = "${{ github.workspace }}/DatabaseAdministration/SSRS/Reports/SalesAnalysisReport.rdl"
          $reportServerUrl = "http://desktop-pl72rr2/ReportServer"
          $reportServerFolder = "/Report Folder"
          $reportServerCredentials = "your_username:your_password"
          
          # Specify full path to ReportBuilder.exe with double quotes
          $reportBuilderPath = '"C:\Program Files (x86)\Microsoft Report Builder\MSReportBuilder.exe"'

          # Build command to publish report
          $publishCommand = "$reportBuilderPath /publish:`"$reportPath`" /rs:$reportServerUrl /rf:$reportServerFolder /rc:`"$reportServerCredentials`""

          # Execute the command
          Invoke-Expression -Command $publishCommand
