name: SSIS

on:
  push:
    branches:
      - main

jobs:
  run_sql_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove conflicting package and update package lists
        run: |
          sudo apt-get remove containerd.io -y
          sudo apt-get update

      - name: Install Docker
        run: sudo apt-get install docker.io -y

      - name: Run MSSQL Server
        run: |
          sudo docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=${{secrets.DK_PASSWORD}}' -p ${{secrets.DK_PORT}} --name sql1 -d mcr.microsoft.com/mssql/server:2019-latest

      - name: Wait for MSSQL to start
        run: sleep 30

      - name: Start Docker container if not running
        run: sudo docker ps -a | grep -q 'sql1' && sudo docker start sql1 || true

      - name: Check if catalog exists and create one
        run: |
          if sqlcmd -S localhost -U sa -P ${{secrets.DK_PASSWORD}} -Q "IF NOT EXISTS (SELECT * FROM sys.catalogs WHERE name = 'SSISDB') SELECT 'Catalog does not exist';" | grep -q "Catalog does not exist"; then
             sqlcmd -S localhost -U sa -P ${{secrets.DK_PASSWORD}} -Q "CREATE CATALOG SSISDB"
             echo "Catalog created successfully."
          else
            echo "Catalog already exists."
          fi

      - name: Deploy SSIS package
        run: |
          sqlcmd -S localhost -U sa -P ${{secrets.DK_PASSWORD}} -d SSISDB -i "DatabaseAdministration/SSIS/Integration Services Project/bin/Development/Integration Services Project.ispac"
