name: Deploy Package

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build Docker image
        run: docker build -t sql-env .
        working-directory: ${{ github.workspace }}
        
      - name: Run SQL environment container
        run: docker run -d --name sql-container -p 1433:1433 sql-env
          
      - name: Check if catalog exists
        id: check_catalog
        run: docker exec sql-container /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourPassword -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'SSISDB') CREATE DATABASE [SSISDB]"
          
      - name: Deploy SSIS package
        run: docker exec sql-container /opt/mssql-tools/bin/ISDeploymentWizard /S localhost /D SSISDB /A ProjectDeploy /ModelType:Project /ProjectPath:"/DatabaseAdministration/SSIS/Practice Activity 2/bin/Development/Practice Activity 2.ispac" /ISServerOption:Native
        if: steps.check_catalog.outputs.returncode == 0
