name: Deploy SSIS Project

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch. Adjust as needed.

jobs:
  deploy:
    runs-on: windows-latest  # Use a Windows runner to execute PowerShell scripts.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Action to checkout your repository's code.

      - name: Setup .NET Core  # Optional, if .NET Core is needed.
        uses: actions/setup-dotnet@v1

      - name: Install SQL Server module
        run: |
          Install-Module -Name SqlServer -Force -AllowClobber
          Import-Module SqlServer

      - name: Run PowerShell script
        shell: pwsh  # Specify PowerShell as the shell for this step.
        run: |
          $SSISNamespace = "Microsoft.SqlServer.Management.IntegrationServices"
          $TargetServerName = "DESKTOP-PL72RR2"
          $TargetFolderName = "SSISWorking"
          $ProjectFilePath = "DatabaseAdministration/SSIS/SSISWorking/bin/Development/SSISWorking.ispac" # Update this path accordingly.
          $ProjectName = "SSISWorking"

          # Load the IntegrationServices assembly
          [System.Reflection.Assembly]::Load("Microsoft.SQLServer.Management.IntegrationServices, "+
              "Version=16.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL") | Out-Null

          # Create a connection to the server
          $sqlConnectionString = "Data Source=$TargetServerName;Initial Catalog=master;Integrated Security=SSPI;"
          $sqlConnection = New-Object System.Data.SqlClient.SqlConnection $sqlConnectionString

          # Create the Integration Services object
          $integrationServices = New-Object $SSISNamespace".IntegrationServices" $sqlConnection

          # Get the Integration Services catalog
          $catalog = $integrationServices.Catalogs["SSISDB"]

          # Create the target folder
          $folder = New-Object $SSISNamespace".CatalogFolder" ($catalog, $TargetFolderName, "Folder description")
          $folder.Create()

          Write-Host "Deploying $ProjectName project ..."

          # Read the project file and deploy it
          $projectFile = [System.IO.File]::ReadAllBytes($ProjectFilePath)
          $folder.DeployProject($ProjectName, $projectFile)
