name: SSIS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_ssis_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQLCMD
        run: sudo apt-get install -y mssql-tools unixodbc-dev

      - name: Deploy SSIS package
        run: |
          sqlcmd -S DESKTOP-PL72RR2 -U User -P Issa100@ -d SSISDB -i "DatabaseAdministration/SSIS/Integration Services Project/bin/Development/Integration Services Project.ispac"
