name: Move SSRS Files to GitHub

on:
  push:
    paths:
      - 'DatabaseAdministration/SSRS/**'  # Trigger only when changes occur within the SSRS folder

jobs:
  move_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Copy files to target directory
      run: |
        rsync -av --exclude='.git' C:/Users/NdivhudzannyiT/Documents/Ndivhu_Tshikho/DatabaseAdministration/SSRS/ DatabaseAdministration/SSRS/
        
    - name: Configure git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        
    - name: Commit changes
      run: |
        git add .
        git commit -m "Move SSRS files to GitHub"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
